import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create(
    {
        mainView: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#372775',
        },
        headerView1: {
        flex: 0.15,
        flexDirection: 'row',
        justifyContent: 'center',
        alignSelf: 'stretch',
        alignItems: 'center',
        },
        headerView2: {
        flex: 0.15,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignSelf: 'stretch',
        alignItems: 'center',
        backgroundColor: '#2B1D62',
        },
        bodyView: {
        flex: 0.60,
        alignSelf: 'stretch',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        },
        bodyView2: {
        flex: 0.75,
        alignSelf: 'stretch',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        },
        bodyView3: {
        flex: 0.85,
        alignSelf: 'stretch',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        },
        footerView: {
        flex: 0.25,
        flexDirection: 'column',
        justifyContent: 'center',
        alignSelf: 'stretch',
        alignItems: 'center',
        padding: 10,
        },
        footerView2: {
        flex: 0.10,
        flexDirection: 'column',
        justifyContent: 'center',
        alignSelf: 'stretch',
        alignItems: 'center',
        padding: 10,
        },
        titleText: {
        fontFamily: 'AveriaLibre-Regular',
        fontSize: 36,
        color: 'white',
        },
        subView1: {
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignSelf: 'stretch',
        padding: 10,
        },
        subView2: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 10,
        },
        subView3: {
        flexDirection: 'row',
        padding: 10,
        },
        card: {
        width: 250,
        aspectRatio: 1/1,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        margin: 20,
        backgroundColor: 'white',
        borderRadius: 10,
        overflow: 'hidden',
        padding:20
        },
        cardText1: {
        fontSize: 20,
        color: '#3F92C5',
        fontFamily: 'AveriaLibre-Regular',
        textAlign:'center'
        },
        cardText2: {
        fontSize: 15,
        color: '#8B8B8B',
        fontFamily: 'AveriaLibre-Regular',
        },
        subText1: {
        fontSize: 20,
        color: 'white',
        fontFamily: 'AveriaLibre-Regular',
        },
        subText2: {
        fontSize: 20,
        color: '#FD7979',
        fontFamily: 'AveriaLibre-Regular',
        },
        textInput: {
        fontSize: 20,
        backgroundColor: 'white',
        alignSelf: 'stretch',
        color: '#3F92C5',
        fontFamily: 'AveriaLibre-Regular',
        borderRadius:3,
        },
        button1: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'stretch',
        backgroundColor: '#37BD6D',
        marginVertical: 20,
        borderRadius:3,
        },
        button2: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'stretch',
        backgroundColor: '#419ED7',
        marginVertical: 10,
        borderRadius:3,
        },
        button3: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'stretch',
        backgroundColor: '#B0CCDE',
        marginVertical: 10,
        borderRadius:3,
        },
        button4: { //botão apagar pesquisa
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'stretch',
        backgroundColor: '#B0CCDE',
        marginVertical: 10,
        },
        button5: {
        width: 250,
        aspectRatio: 1/1,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        margin: 20,
        backgroundColor: '#312464',
        borderRadius: 10,
        overflow: 'hidden',
        },
        button6: {
        width: 150,
        aspectRatio: 1/1,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        margin: 20,
        overflow: 'hidden',
        },
        button7: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        margin: 20,
        paddingLeft: 30
        },
        button8: {
        width: 200,
        height: 50,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'stretch',
        backgroundColor: '#37BD6D',
        marginVertical: 20,
        borderRadius:3,
        },
        button9: {
        flexDirection: 'row',
        alignSelf: 'stretch',
        margin: 10
        },
        textButton1: {
        fontSize: 20,
        color: 'white',
        paddingVertical: 10,
        fontFamily: 'AveriaLibre-Regular',
        },
        textButton2: {
        fontSize: 15,
        color: 'white',
        paddingVertical: 10,
        fontFamily: 'AveriaLibre-Regular',
        },
        text1: {
        fontSize: 40,
        color: 'white',
        textAlign: 'center',
        fontFamily: 'AveriaLibre-Regular',
        },
        captionColor: {
        aspectRatio: 1/1,
        width: 25,
        marginRight:15
        },
        modal: {
        width: 300,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        padding: 30,
        overflow: 'hidden',
        backgroundColor: '#2B1F5C',
        borderRadius: 3
        },
        drawer: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        overflow: 'hidden',
        padding: 40
        },
        drawerButtons: {
        flexDirection: 'column',
        justifyContent: 'flex-start',
        width: 300,
        alignItems: 'center',
        alignSelf: 'center',
        overflow: 'hidden'
        }
    }
)